md "Todos os paises"
cd "Todos os paises"
md "Argentina"
md "Bolivia"
md "Brasil" 
md "Chile"
md "Colombia"
md "Equador"
md "Guiana"
md "Guiana Francesa"
md "Paraguai"
md "Peru"
md "Suriname"
md "Uruguai"
md "Venezuela"

cd "Brasil"
md "Distrito Federal"
md "Goias"
md "Mato Grosso"
md "Mato Grosso do Sul"
md "Alagoas"
md "Bahia" 
md "Ceara"
md "Maranhao"
md "Paraiba"
md "Pernambuco"
md "Piaui"
md "Rio Grande do Norte"
md "Sergipe"
md "Acre"
md "Amapa" 
md "Amazonas"
md "Para" 
md "Rondonia"
md "Roraima"
md "Tocantins"
md "São Paulo"
md "Rio de Janeiro
md "Minas Gerais"
md "Espírito Santo"
md "Parana"
md "Santa Catarina"
md "Rio Grande do Sul"